bspline_6d_constructor_specify_knots – bspline-fortran
bspline_6d_constructor_specify_knots Function
25 statements
Source File
private pure function bspline_6d_constructor_specify_knots(x, y, z, q, r, s, fcn, kx, ky, kz, kq, kr, ks, tx, ty, tz, tq, tr, ts, extrap) result(me)
Constructor for a bspline_6d type (user-specified knots). This is a wrapper for initialize_6d_specify_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: z
(nz) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: q
(nq) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: r
(nr) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: s
(ns) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:,:,:,:,:) :: fcn
(nx,ny,nz,nq,nr,ns) matrix of function values to interpolate. fcn(i,j,k,l,m,n) should contain the function value at the point (x(i),y(j),z(k),q(l),r(m),s(n))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kz
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kq
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kr
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ks
The order of spline pieces in () (order = polynomial degree + 1)
real(kind=wp), intent(in), dimension(:) :: tx
The (nx+kx) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: ty
The (ny+ky) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: tz
The (nz+kz) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: tq
The (nq+kq) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: tr
The (nr+kr) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: ts
The (ns+ks) knots in the direction for the spline interpolant. Must be non-decreasing.
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_6d)
Calls
Called by
Contents
Source Code
bspline_6d_constructor_specify_knots
Source Code
    pure function bspline_6d_constructor_specify_knots(x,y,z,q,r,s,fcn,&
                                                        kx,ky,kz,kq,kr,ks,&
                                                        tx,ty,tz,tq,tr,ts,extrap) result(me)
    implicit none
    type(bspline_6d)                           :: me
    real(wp),dimension(:),intent(in)           :: x   !! `(nx)` array of \(x\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in)           :: y   !! `(ny)` array of \(y\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in)           :: z   !! `(nz)` array of \(z\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in)           :: q   !! `(nq)` array of \(q\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in)           :: r   !! `(nr)` array of \(r\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in)           :: s   !! `(ns)` array of \(s\) abcissae. Must be strictly increasing.
    real(wp),dimension(:,:,:,:,:,:),intent(in) :: fcn !! `(nx,ny,nz,nq,nr,ns)` matrix of function values to interpolate.
                                                      !! `fcn(i,j,k,l,m,n)` should contain the function value at the
                                                      !! point (`x(i)`,`y(j)`,`z(k)`,`q(l)`,`r(m)`,`s(n)`)
    integer(ip),intent(in)                     :: kx  !! The order of spline pieces in \(x\)
                                                      !! ( \( 2 \le k_x < n_x \) )
                                                      !! (order = polynomial degree + 1)
    integer(ip),intent(in)                     :: ky  !! The order of spline pieces in \(y\)
                                                      !! ( \( 2 \le k_y < n_y \) )
                                                      !! (order = polynomial degree + 1)
    integer(ip),intent(in)                     :: kz  !! The order of spline pieces in \(z\)
                                                      !! ( \( 2 \le k_z < n_z \) )
                                                      !! (order = polynomial degree + 1)
    integer(ip),intent(in)                     :: kq  !! The order of spline pieces in \(q\)
                                                      !! ( \( 2 \le k_q < n_q \) )
                                                      !! (order = polynomial degree + 1)
    integer(ip),intent(in)                     :: kr  !! The order of spline pieces in \(r\)
                                                      !! ( \( 2 \le k_r < n_r \) )
                                                      !! (order = polynomial degree + 1)
    integer(ip),intent(in)                     :: ks  !! The order of spline pieces in \(z\)
                                                      !! ( \( 2 \le k_z < n_z \) )
                                                      !! (order = polynomial degree + 1)
    real(wp),dimension(:),intent(in)           :: tx  !! The `(nx+kx)` knots in the \(x\) direction
                                                      !! for the spline interpolant.
                                                      !! Must be non-decreasing.
    real(wp),dimension(:),intent(in)           :: ty  !! The `(ny+ky)` knots in the \(y\) direction
                                                      !! for the spline interpolant.
                                                      !! Must be non-decreasing.
    real(wp),dimension(:),intent(in)           :: tz  !! The `(nz+kz)` knots in the \(z\) direction
                                                      !! for the spline interpolant.
                                                      !! Must be non-decreasing.
    real(wp),dimension(:),intent(in)           :: tq  !! The `(nq+kq)` knots in the \(q\) direction
                                                      !! for the spline interpolant.
                                                      !! Must be non-decreasing.
    real(wp),dimension(:),intent(in)           :: tr  !! The `(nr+kr)` knots in the \(r\) direction
                                                      !! for the spline interpolant.
                                                      !! Must be non-decreasing.
    real(wp),dimension(:),intent(in)           :: ts  !! The `(ns+ks)` knots in the \(s\) direction
                                                      !! for the spline interpolant.
                                                      !! Must be non-decreasing.
    logical,intent(in),optional      :: extrap        !! if true, then extrapolation is allowed
                                                      !! (default is false)
    call initialize_6d_specify_knots(me,x,y,z,q,r,s,fcn,&
                                        kx,ky,kz,kq,kr,ks,&
                                        tx,ty,tz,tq,tr,ts,me%iflag,extrap)
    end function bspline_6d_constructor_specify_knots
Call graph
bspline_6d_constructor_specify_knots calls initialize_6d_specify_knots
initialize_6d_specify_knots calls bcoef, destroy, check_knot_vectors_sizes, db6ink, set_extrap_flag, work_val_1, work_val_2, work_val_3, work_val_4, work_val_5, work_val_6
db6ink calls check_inputs, dbknot, dbtpcf
dbtpcf calls dbintk, dbnslv
dbintk calls dbnslv, dbnfac, dbspvn
bspline_6d calls bspline_6d_constructor_specify_knots