bspline_1d_constructor_auto_knots – bspline-fortran
bspline_1d_constructor_auto_knots Function
9 statements
Source File
private pure function bspline_1d_constructor_auto_knots(x, fcn, kx, extrap) result(me)
Constructor for a bspline_1d type (auto knots). This is a wrapper for initialize_1d_auto_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: fcn
(nx) array of function values to interpolate. fcn(i) should contain the function value at the point x(i)
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_1d)
Calls
Called by
Source Code
    pure function bspline_1d_constructor_auto_knots(x,fcn,kx,extrap) result(me)
    implicit none
    type(bspline_1d)                 :: me
    real(wp),dimension(:),intent(in) :: x      !! `(nx)` array of \(x\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in) :: fcn    !! `(nx)` array of function values to interpolate. `fcn(i)` should
                                               !! contain the function value at the point `x(i)`
    integer(ip),intent(in)           :: kx     !! The order of spline pieces in \(x\)
                                               !! ( \( 2 \le k_x < n_x \) )
                                               !! (order = polynomial degree + 1)
    logical,intent(in),optional      :: extrap !! if true, then extrapolation is allowed
                                               !! (default is false)
    call initialize_1d_auto_knots(me,x,fcn,kx,me%iflag,extrap)
    end function bspline_1d_constructor_auto_knots
Call graph
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
initialize_1d_auto_knots calls db1ink, destroy_1d, set_extrap_flag
db1ink calls db1ink_alt, db1ink_alt_2, db1ink_default
destroy_1d calls destroy_base
db1ink_alt calls check_inputs, dbint4
db1ink_alt_2 calls check_inputs, dbint4
db1ink_default calls check_inputs, dbknot, dbtpcf
dbint4 calls dbnfac, dbnslv, dbspvd
dbtpcf calls dbintk, dbnslv
dbintk calls dbnfac, dbnslv, dbspvn
dbspvd calls dbspvn
bspline_1d calls bspline_1d_constructor_auto_knots