bspline_2d_constructor_auto_knots – bspline-fortran
bspline_2d_constructor_auto_knots Function
11 statements
Source File
private pure function bspline_2d_constructor_auto_knots(x, y, fcn, kx, ky, extrap) result(me)
Constructor for a bspline_2d type (auto knots). This is a wrapper for initialize_2d_auto_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:) :: fcn
(nx,ny) matrix of function values to interpolate. fcn(i,j) should contain the function value at the point (x(i),y(j))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_2d)
Calls
Called by
Contents
Source Code
bspline_2d_constructor_auto_knots
Source Code
    pure function bspline_2d_constructor_auto_knots(x,y,fcn,kx,ky,extrap) result(me)
    implicit none
    type(bspline_2d)                   :: me
    real(wp),dimension(:),intent(in)   :: x     !! `(nx)` array of \(x\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in)   :: y     !! `(ny)` array of \(y\) abcissae. Must be strictly increasing.
    real(wp),dimension(:,:),intent(in) :: fcn   !! `(nx,ny)` matrix of function values to interpolate.
                                                !! `fcn(i,j)` should contain the function value at the
                                                !! point (`x(i)`,`y(j)`)
    integer(ip),intent(in)             :: kx    !! The order of spline pieces in \(x\)
                                                !! ( \( 2 \le k_x < n_x \) )
                                                !! (order = polynomial degree + 1)
    integer(ip),intent(in)             :: ky    !! The order of spline pieces in \(y\)
                                                !! ( \( 2 \le k_y < n_y \) )
                                                !! (order = polynomial degree + 1)
    logical,intent(in),optional      :: extrap  !! if true, then extrapolation is allowed
                                                !! (default is false)
    call initialize_2d_auto_knots(me,x,y,fcn,kx,ky,me%iflag,extrap)
    end function bspline_2d_constructor_auto_knots
Call graph
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
initialize_2d_auto_knots calls bcoef, destroy, db2ink, set_extrap_flag, tx, ty, work_val_1, work_val_2
db2ink calls check_inputs, dbknot, dbtpcf
dbtpcf calls dbintk, dbnslv
dbintk calls dbnslv, dbnfac, dbspvn
bspline_2d calls bspline_2d_constructor_auto_knots