dbknot – bspline-fortran
dbknot Subroutine
31 statements
Source File
private pure subroutine dbknot(x, n, k, t)
dbknot chooses a knot sequence for interpolation of order k at the data points x(i), i=1,..,n. the n+k knots are placed in the array t. k knots are placed at each endpoint and not-a-knot end conditions are used. the remaining knots are placed at data points if n is even and between data points if n is odd. the rightmost knot is shifted slightly to the right to insure proper interpolation at x(n) (see page 350 of the reference).
History
Jacob Williams, 2/24/2015 : Refactored this routine.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
integer(kind=ip), intent(in) :: n
dimension of x
integer(kind=ip), intent(in) :: k
real(kind=wp), intent(out), dimension(:) :: t
Called by
Contents
Source Code
dbknot
Source Code
    pure subroutine dbknot(x,n,k,t)
    implicit none
    integer(ip),intent(in)             :: n  !! dimension of `x`
    integer(ip),intent(in)             :: k
    real(wp),dimension(:),intent(in)   :: x
    real(wp),dimension(:),intent(out)  :: t
    integer(ip) :: i, j, ipj, npj, ip1, jstrt
    real(wp) :: rnot
    !put k knots at each endpoint
    !(shift right endpoints slightly -- see pg 350 of reference)
    rnot = x(n) + 0.1_wp*( x(n)-x(n-1_ip) )
    do j=1_ip,k
        t(j)   = x(1_ip)
        npj    = n + j
        t(npj) = rnot
    end do
    !distribute remaining knots
    if (mod(k,2_ip) == 1_ip)  then
        !case of odd k --  knots between data points
        i = (k-1_ip)/2_ip - k
        ip1 = i + 1_ip
        jstrt = k + 1_ip
        do j=jstrt,n
            ipj = i + j
            t(j) = 0.5_wp*( x(ipj) + x(ipj+1_ip) )
        end do
    else
        !case of even k --  knots at data points
        i = (k/2_ip) - k
        jstrt = k+1_ip
        do j=jstrt,n
            ipj = i + j
            t(j) = x(ipj)
        end do
    end if
    end subroutine dbknot
Call graph
db4ink calls dbknot
db6ink calls dbknot
db3ink calls dbknot
db2ink calls dbknot
db1ink_default calls dbknot
db5ink calls dbknot
initialize_6d_auto_knots calls db6ink
initialize_4d_specify_knots calls db4ink
initialize_6d_specify_knots calls db6ink
initialize_3d_specify_knots calls db3ink
db1ink calls db1ink_default
initialize_5d_specify_knots calls db5ink
initialize_4d_auto_knots calls db4ink
initialize_3d_auto_knots calls db3ink
initialize_2d_auto_knots calls db2ink
initialize_2d_specify_knots calls db2ink
initialize_5d_auto_knots calls db5ink
bspline_6d_constructor_auto_knots calls initialize_6d_auto_knots
bspline_6d_constructor_specify_knots calls initialize_6d_specify_knots
initialize_1d_auto_knots calls db1ink
initialize_1d_specify_knots calls db1ink
bspline_3d_constructor_auto_knots calls initialize_3d_auto_knots
bspline_5d_constructor_auto_knots calls initialize_5d_auto_knots
bspline_4d_constructor_specify_knots calls initialize_4d_specify_knots
bspline_3d_constructor_specify_knots calls initialize_3d_specify_knots
bspline_5d_constructor_specify_knots calls initialize_5d_specify_knots
bspline_4d_constructor_auto_knots calls initialize_4d_auto_knots
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_2d_constructor_specify_knots calls initialize_2d_specify_knots
bspline_6d calls bspline_6d_constructor_auto_knots, bspline_6d_constructor_specify_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_3d calls bspline_3d_constructor_auto_knots, bspline_3d_constructor_specify_knots
bspline_5d calls bspline_5d_constructor_auto_knots, bspline_5d_constructor_specify_knots
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_4d calls bspline_4d_constructor_specify_knots, bspline_4d_constructor_auto_knots
bspline_2d calls bspline_2d_constructor_auto_knots, bspline_2d_constructor_specify_knots
bspline_1d calls bspline_1d_constructor_specify_knots, bspline_1d_constructor_auto_knots