dbtpcf – bspline-fortran
dbtpcf Subroutine
37 statements
Source File
private pure subroutine dbtpcf(x, n, fcn, ldf, nf, t, k, bcoef, work, iflag)
dbtpcf computes b-spline interpolation coefficients for nf sets of data stored in the columns of the array fcn. the b-spline coefficients are stored in the rows of bcoef however. each interpolation is based on the n abcissa stored in the array x, and the n+k knots stored in the array t. the order of each interpolation is k.
History
Jacob Williams, 2/24/2015 : Refactored this routine.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
integer(kind=ip), intent(in) :: n
dimension of x
real(kind=wp), intent(in), dimension(ldf,nf) :: fcn
integer(kind=ip), intent(in) :: ldf
integer(kind=ip), intent(in) :: nf
real(kind=wp), intent(in), dimension(:) :: t
integer(kind=ip), intent(in) :: k
real(kind=wp), intent(out), dimension(nf,n) :: bcoef
real(kind=wp), intent(out), dimension(*) :: work
work array of size >= 2*k*(n+1)
integer(kind=ip), intent(out) :: iflag
status flag:
0: no errors
301: n should be >0
Calls
Called by
Source Code
    pure subroutine dbtpcf(x,n,fcn,ldf,nf,t,k,bcoef,work,iflag)
    integer(ip),intent(in)                :: n  !! dimension of `x`
    integer(ip),intent(in)                :: nf
    integer(ip),intent(in)                :: ldf
    integer(ip),intent(in)                :: k
    real(wp),dimension(:),intent(in)      :: x
    real(wp),dimension(ldf,nf),intent(in) :: fcn
    real(wp),dimension(:),intent(in)      :: t
    real(wp),dimension(nf,n),intent(out)  :: bcoef
    real(wp),dimension(*),intent(out)     :: work   !! work array of size >= `2*k*(n+1)`
    integer(ip),intent(out)               :: iflag  !! status flag:
                                                    !!
                                                    !! * 0: no errors
                                                    !! * 301: n should be >0
    integer(ip) :: i, j, m1, m2, iq, iw
    ! check for null input
    if (nf > 0_ip)  then
        ! partition work array
        m1 = k - 1_ip
        m2 = m1 + k
        iq = 1_ip + n
        iw = iq + m2*n+1_ip
        ! compute b-spline coefficients
        ! first data set
        call dbintk(x,fcn,t,n,k,work,work(iq),work(iw),iflag)
        if (iflag == 0_ip) then
            do i=1_ip,n
                bcoef(1_ip,i) = work(i)
            end do
            !  all remaining data sets by back-substitution
            if (nf == 1_ip)  return
            do j=2_ip,nf
                do i=1_ip,n
                    work(i) = fcn(i,j)
                end do
                call dbnslv(work(iq),m2,n,m1,m1,work)
                do i=1_ip,n
                    bcoef(j,i) = work(i)
                end do
            end do
        end if
    else
        !write(error_unit,'(A)') 'dbtpcf - n should be >0'
        iflag = 301_ip
    end if
    end subroutine dbtpcf
Call graph
dbtpcf calls dbintk, dbnslv
dbintk calls dbnslv, dbnfac, dbspvn
db1ink_default calls dbtpcf
db2ink calls dbtpcf
db3ink calls dbtpcf
db4ink calls dbtpcf
db5ink calls dbtpcf
db6ink calls dbtpcf
db1ink calls db1ink_default
initialize_2d_auto_knots calls db2ink
initialize_2d_specify_knots calls db2ink
initialize_3d_auto_knots calls db3ink
initialize_3d_specify_knots calls db3ink
initialize_4d_auto_knots calls db4ink
initialize_4d_specify_knots calls db4ink
initialize_5d_auto_knots calls db5ink
initialize_5d_specify_knots calls db5ink
initialize_6d_auto_knots calls db6ink
initialize_6d_specify_knots calls db6ink
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_2d_constructor_specify_knots calls initialize_2d_specify_knots
bspline_3d_constructor_auto_knots calls initialize_3d_auto_knots
bspline_3d_constructor_specify_knots calls initialize_3d_specify_knots
bspline_4d_constructor_auto_knots calls initialize_4d_auto_knots
bspline_4d_constructor_specify_knots calls initialize_4d_specify_knots
bspline_5d_constructor_auto_knots calls initialize_5d_auto_knots
bspline_5d_constructor_specify_knots calls initialize_5d_specify_knots
bspline_6d_constructor_auto_knots calls initialize_6d_auto_knots
bspline_6d_constructor_specify_knots calls initialize_6d_specify_knots
initialize_1d_auto_knots calls db1ink
initialize_1d_specify_knots calls db1ink
bspline_2d calls bspline_2d_constructor_auto_knots, bspline_2d_constructor_specify_knots
bspline_3d calls bspline_3d_constructor_auto_knots, bspline_3d_constructor_specify_knots
bspline_4d calls bspline_4d_constructor_auto_knots, bspline_4d_constructor_specify_knots
bspline_5d calls bspline_5d_constructor_auto_knots, bspline_5d_constructor_specify_knots
bspline_6d calls bspline_6d_constructor_auto_knots, bspline_6d_constructor_specify_knots
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_specify_knots