destroy_4d – bspline-fortran
destroy_4d Subroutine
27 statements
Source File
private pure subroutine destroy_4d(me)
Destructor for bspline_4d class.
Type Bound
bspline_4d
Arguments
Type Intent Optional Attributes Name
class(bspline_4d), intent(inout) :: me
Called by
Source Code
    pure subroutine destroy_4d(me)
    implicit none
    class(bspline_4d),intent(inout) :: me
    me%nx    = 0_ip
    me%ny    = 0_ip
    me%nz    = 0_ip
    me%nq    = 0_ip
    me%kx    = 0_ip
    me%ky    = 0_ip
    me%kz    = 0_ip
    me%kq    = 0_ip
    me%inbvy = 1_ip
    me%inbvz = 1_ip
    me%inbvq = 1_ip
    me%iloy  = 1_ip
    me%iloz  = 1_ip
    me%iloq  = 1_ip
    if (allocated(me%bcoef))      deallocate(me%bcoef)
    if (allocated(me%tx))         deallocate(me%tx)
    if (allocated(me%ty))         deallocate(me%ty)
    if (allocated(me%tz))         deallocate(me%tz)
    if (allocated(me%tq))         deallocate(me%tq)
    if (allocated(me%work_val_1)) deallocate(me%work_val_1)
    if (allocated(me%work_val_2)) deallocate(me%work_val_2)
    if (allocated(me%work_val_3)) deallocate(me%work_val_3)
    if (allocated(me%work_val_4)) deallocate(me%work_val_4)
    end subroutine destroy_4d
Call graph
finalize_4d calls destroy_4d
initialize_4d_auto_knots calls destroy_4d
initialize_4d_specify_knots calls destroy_4d
bspline_4d_constructor_auto_knots calls initialize_4d_auto_knots
bspline_4d_constructor_specify_knots calls initialize_4d_specify_knots
bspline_4d calls bspline_4d_constructor_auto_knots, bspline_4d_constructor_specify_knots