destroy_base – bspline-fortran
destroy_base Subroutine
8 statements
Source File
private pure subroutine destroy_base(me)
Destructor for contents of the base bspline_class class. (this routine is called by the extended classes).
Type Bound
bspline_class
Arguments
Type Intent Optional Attributes Name
class(bspline_class), intent(inout) :: me
Called by
Source Code
    pure subroutine destroy_base(me)
    implicit none
    class(bspline_class),intent(inout) :: me
    me%inbvx = 1_ip
    me%iflag = 1_ip
    me%initialized = .false.
    me%extrap = .false.
    end subroutine destroy_base
Call graph
destroy_1d calls destroy_base
destroy_2d calls destroy_base
destroy_3d calls destroy_base
finalize_1d calls destroy_1d
finalize_2d calls destroy_2d
finalize_3d calls destroy_3d
initialize_1d_auto_knots calls destroy_1d
initialize_1d_specify_knots calls destroy_1d
initialize_2d_auto_knots calls destroy_2d
initialize_2d_specify_knots calls destroy_2d
initialize_3d_auto_knots calls destroy_3d
initialize_3d_specify_knots calls destroy_3d
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_2d_constructor_specify_knots calls initialize_2d_specify_knots
bspline_3d_constructor_auto_knots calls initialize_3d_auto_knots
bspline_3d_constructor_specify_knots calls initialize_3d_specify_knots
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_specify_knots
bspline_2d calls bspline_2d_constructor_auto_knots, bspline_2d_constructor_specify_knots
bspline_3d calls bspline_3d_constructor_auto_knots, bspline_3d_constructor_specify_knots