dlsi – bspline-fortran
dlsi Subroutine
177 statements
Source File
private subroutine dlsi(w, mdw, ma, mg, n, prgopt, x, rnorm, mode, ws, ipp)
This is a companion subprogram to dlsei. The documentation for dlsei has complete usage instructions.
Solve:
    AX = B,  A  MA by N  (least squares equations)
subject to:
    GX>=H, G  MG by N  (inequality constraints)
Revision history
790701 DATE WRITTEN. Hanson, R. J., (SNLA)
890531 Changed all specific intrinsics to generic. (WRB)
890618 Completely restructured and extensively revised (WRB & RWC)
891214 Prologue converted to Version 4.0 format. (BAB)
900328 Added TYPE section. (WRB)
900604 DP version created from SP version. (RWC)
920422 Changed CALL to DHFTI to include variable MA. (WRB)
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: w(mdw,*)
W(*,*) contains:
 (A B)
 (G H)
in rows 1,...,MA+MG, cols 1,...,N+1.
integer(kind=ip), intent(in) :: mdw
contain (resp) var. dimension of W(*,*), and matrix dimensions.
integer(kind=ip), intent(in) :: ma
contain (resp) var. dimension of W(*,*), and matrix dimensions.
integer(kind=ip), intent(in) :: mg
contain (resp) var. dimension of W(*,*), and matrix dimensions.
integer(kind=ip), intent(in) :: n
contain (resp) var. dimension of W(*,*), and matrix dimensions.
real(kind=wp), intent(in) :: prgopt(*)
Program option vector.
real(kind=wp), intent(out) :: x(*)
Solution vector(unless MODE=2)
real(kind=wp), intent(out) :: rnorm
length of AX-B.
integer(kind=ip), intent(out) :: mode
=0 Inequality constraints are compatible.
=2 Inequality constraints contradictory.
real(kind=wp) :: ws(*)
Working storage of dimension K+N+(MG+2)*(N+7), where K=MAX(MA+MG,N).
integer(kind=ip) :: ipp(*)
ipp(MG+2*N+1) Integer working storage
Calls
Called by
Source Code
   subroutine dlsi (w, mdw, ma, mg, n, prgopt, x, rnorm, mode, ws, ipp)
   integer(ip),intent(in) :: mdw !! contain (resp) var. dimension of `W(*,*)`, and matrix dimensions.
   integer(ip),intent(in) :: ma  !! contain (resp) var. dimension of `W(*,*)`, and matrix dimensions.
   integer(ip),intent(in) :: mg  !! contain (resp) var. dimension of `W(*,*)`, and matrix dimensions.
   integer(ip),intent(in) :: n   !! contain (resp) var. dimension of `W(*,*)`, and matrix dimensions.
   real(wp) :: w(mdw,*) !! `W(*,*)` contains:
                        !!
                        !!```
                        !! (A B)
                        !! (G H)
                        !!```
                        !!
                        !! in rows `1,...,MA+MG`,
                        !! cols `1,...,N+1`.
   real(wp),intent(in) :: prgopt(*) !! Program option vector.
   real(wp),intent(out) :: x(*) !! Solution vector(unless MODE=2)
   real(wp),intent(out) :: rnorm !! length of AX-B.
   integer(ip),intent(out) :: mode !! * `=0`   Inequality constraints are compatible.
                               !! * `=2`   Inequality constraints contradictory.
   real(wp) :: ws(*) !! Working storage of dimension `K+N+(MG+2)*(N+7)`,
                     !! where `K=MAX(MA+MG,N)`.
   integer(ip) :: ipp(*) !! `ipp(MG+2*N+1)` Integer working storage
   real(wp) :: anorm, fac, gam, rb, tau, tol, xnorm
   integer(ip) :: i, j, k, key, krank, krm1, krp1, l, last, link, m, map1, &
              mdlpdp, minman, n1, n2, n3, next, np1
   logical :: cov, sclcov
   real(wp) :: rnorm_(1) !! JW added for call to [[dhfti]]
   ! Set the nominal tolerance used in the code.
   tol = sqrt(drelpr)
   mode = 0
   rnorm = 0.0_wp
   m = ma + mg
   np1 = n + 1
   krank = 0
   main : block
      if (n<=0 .or. m<=0) exit main
      ! To process option vector.
      cov = .false.
      sclcov = .true.
      last = 1
      link = prgopt(1)
      do
         if (link<=1) exit
         key = prgopt(last+1)
         if (key==1) cov = prgopt(last+2) /= 0.0_wp
         if (key==10) sclcov = prgopt(last+2) == 0.0_wp
         if (key==5) tol = max(drelpr,prgopt(last+2))
         next = prgopt(link)
         last = link
         link = next
      end do
      ! Compute matrix norm of least squares equations.
      anorm = 0.0_wp
      do j = 1,n
         anorm = max(anorm,dasum(ma,w(1,j),1_ip))
      end do
      ! Set tolerance for DHFTI( ) rank test.
      tau = tol*anorm
      ! Compute Householder orthogonal decomposition of matrix.
      call dcopy (n, [0.0_wp], 0_ip, ws, 1_ip)
      call dcopy (ma, w(1, np1), 1_ip, ws, 1_ip)
      k = max(m,n)
      minman = min(ma,n)
      n1 = k + 1
      n2 = n1 + n
      rnorm_(1) = rnorm ! JW
      call dhfti (w, mdw, ma, n, ws, ma, 1_ip, tau, krank, rnorm_, ws(n2), &
                  ws(n1), ipp)
      rnorm = rnorm_(1) ! JW
      fac = 1.0_wp
      gam = ma - krank
      if (krank<ma .and. sclcov) fac = rnorm**2/gam
      ! Reduce to DLPDP and solve.
      map1 = ma + 1
      ! Compute inequality rt-hand side for DLPDP.
      if (ma<m) then
         if (minman>0) then
            do i = map1,m
               w(i,np1) = w(i,np1) - ddot(n,w(i,1),mdw,ws,1_ip)
            end do
            ! Apply permutations to col. of inequality constraint matrix.
            do i = 1,minman
               call dswap (mg, w(map1,i), 1_ip, w(map1,ipp(i)), 1_ip)
            end do
            ! Apply Householder transformations to constraint matrix.
            if (krank>0 .and. krank<n) then
               do i = krank,1,-1
                  call dh12 (2_ip, i, krank+1, n, w(i,1), mdw, ws(n1+i-1), &
                             w(map1,1), mdw, 1_ip, mg)
               end do
            endif
            ! Compute permuted inequality constraint matrix times r-inv.
            do i = map1,m
               do j = 1,krank
                  w(i,j) = (w(i,j)-ddot(j-1,w(1,j),1_ip,w(i,1),mdw))/w(j,j)
               end do
         end do
         endif
         ! Solve the reduced problem with DLPDP algorithm,
         ! the least projected distance problem.
         call dlpdp(w(map1,1), mdw, mg, krank, n-krank, prgopt, x, &
                    xnorm, mdlpdp, ws(n2), ipp(n+1))
         ! Compute solution in original coordinates.
         if (mdlpdp==1) then
            do i = krank,1,-1
               x(i) = (x(i)-ddot(krank-i,w(i,i+1),mdw,x(i+1),1_ip))/w(i,i)
            end do
            ! Apply Householder transformation to solution vector.
            if (krank<n) then
               do i = 1,krank
                  call dh12 (2_ip, i, krank+1, n, w(i,1), mdw, ws(n1+i-1), &
                             x, 1_ip, 1_ip, 1_ip)
               end do
            endif
            ! Repermute variables to their input order.
            if (minman>0) then
               do i = minman,1,-1
                  call dswap (1_ip, x(i), 1_ip, x(ipp(i)), 1_ip)
               end do
               ! Variables are now in original coordinates.
               ! Add solution of unconstrained problem.
               do i = 1,n
                  x(i) = x(i) + ws(i)
               end do
               ! Compute the residual vector norm.
               rnorm = sqrt(rnorm**2+xnorm**2)
            endif
         else
            mode = 2
         endif
      else
         call dcopy (n, ws, 1_ip, x, 1_ip)
      endif
      ! Compute covariance matrix based on the orthogonal decomposition
      ! from DHFTI( ).
      if (.not.cov .or. krank<=0) exit main
      krm1 = krank - 1
      krp1 = krank + 1
      ! Copy diagonal terms to working array.
      call dcopy (krank, w, mdw+1, ws(n2), 1_ip)
      ! Reciprocate diagonal terms.
      do j = 1,krank
         w(j,j) = 1.0_wp/w(j,j)
      end do
      ! Invert the upper triangular QR factor on itself.
      if (krank>1) then
         do i = 1,krm1
            do j = i+1,krank
               w(i,j) = -ddot(j-i,w(i,i),mdw,w(i,j),1_ip)*w(j,j)
            end do
         end do
      endif
      ! Compute the inverted factor times its transpose.
      do i = 1,krank
         do j = i,krank
            w(i,j) = ddot(krank+1-j,w(i,j),mdw,w(j,j),mdw)
         end do
      end do
      ! Zero out lower trapezoidal part.
      ! Copy upper triangular to lower triangular part.
      if (krank<n) then
         do j = 1,krank
            call dcopy (j, w(1,j), 1_ip, w(j,1), mdw)
         end do
         do i = krp1,n
            call dcopy (i, [0.0_wp], 0_ip, w(i,1), mdw)
         end do
         ! Apply right side transformations to lower triangle.
         n3 = n2 + krp1
         do i = 1,krank
            l = n1 + i
            k = n2 + i
            rb = ws(l-1)*ws(k-1)
            ! If RB>=0.0_wp, transformation can be regarded as zero.
            if (rb<0.0_wp) then
               rb = 1.0_wp/rb
               ! Store unscaled rank one Householder update in work array.
               call dcopy (n, [0.0_wp], 0_ip, ws(n3), 1_ip)
               l = n1 + i
               k = n3 + i
               ws(k-1) = ws(l-1)
               do j = krp1,n
                  ws(n3+j-1) = w(i,j)
               end do
               do j = 1,n
                  ws(j) = rb*(ddot(j-i,w(j,i),mdw,ws(n3+i-1),1_ip)+ &
                        ddot(n-j+1,w(j,j),1_ip,ws(n3+j-1),1_ip))
               end do
               l = n3 + i
               gam = 0.5_wp*rb*ddot(n-i+1,ws(l-1),1_ip,ws(i),1_ip)
               call daxpy (n-i+1_ip, gam, ws(l-1), 1_ip, ws(i), 1_ip)
               do j = i,n
                  do l = 1,i-1
                     w(j,l) = w(j,l) + ws(n3+j-1)*ws(l)
                  end do
                  do l = i,j
                     w(j,l) = w(j,l) + ws(j)*ws(n3+l-1)+ws(l)*ws(n3+j-1)
                  end do
               end do
            endif
         end do
         ! Copy lower triangle to upper triangle to symmetrize the
         ! covariance matrix.
         do i = 1,n
            call dcopy (i, w(i,1), mdw, w(1,i), 1_ip)
         end do
      endif
      ! Repermute rows and columns.
      do i = minman,1,-1
         k = ipp(i)
         if (i/=k) then
            call dswap (1_ip, w(i,i), 1_ip, w(k,k), 1_ip)
            call dswap (i-1_ip, w(1,i), 1_ip, w(1,k), 1_ip)
            call dswap (k-i-1_ip, w(i,i+1), mdw, w(i+1,k), 1_ip)
            call dswap (n-k, w(i, k+1), mdw, w(k, k+1), mdw)
         endif
      end do
      ! Put in normalized residual sum of squares scale factor
      ! and symmetrize the resulting covariance matrix.
      do j = 1,n
         call dscal (j, fac, w(1,j), 1_ip)
         call dcopy (j, w(1,j), 1_ip, w(j,1), mdw)
      end do
   end block main
   ipp(1) = krank
   ipp(2) = n + max(m,n) + (mg+2)*(n+7)
   end subroutine dlsi
Call graph
dlsi calls dasum, daxpy, dcopy, ddot, dh12, dhfti, dlpdp, dscal, dswap
dh12 calls daxpy, ddot, dswap
dhfti calls dh12
dlpdp calls dcopy, ddot, dscal, dnrm2, dwnnls
dwnnls calls dwnlsm
dwnlsm calls dasum, daxpy, dcopy, dh12, dscal, dswap, dnrm2, drotm, drotmg, dwnlit, idamax
dwnlit calls dcopy, dh12, dscal, dswap, drotm, drotmg, idamax, dwnlt1, dwnlt2, dwnlt3
dwnlt1 calls idamax
dwnlt3 calls dswap
dlsei calls dlsi
dfcmn calls dlsei
dfc calls dfcmn