dnrm2 – bspline-fortran
dnrm2 Function
66 statements
Source File
public function dnrm2(n, x, incx)
returns the euclidean norm of a vector
Arguments
Type Intent Optional Attributes Name
integer(kind=ip) :: n
real(kind=wp) :: x(*)
integer(kind=ip) :: incx
Return Value real(kind=wp)
Called by
Call graph
dlpdp calls dnrm2, dwnnls
dlsei calls dnrm2, dlsi
dwnlsm calls dnrm2
dfcmn calls dlsei
dlsi calls dlpdp
dwnnls calls dwnlsm
dfc calls dfcmn