dwnlt3 – bspline-fortran
dwnlt3 Subroutine
20 statements
Source File
private subroutine dwnlt3(i, imax, m, mdw, ipivot, h, w)
Perform column interchange. Exchange elements of permuted index vector and perform column interchanges.
Revision history
790701 DATE WRITTEN. Hanson, R. J., (SNLA), Haskell, K. H., (SNLA)
890620 Code extracted from WNLIT and made a subroutine. (RWC))
900604 DP version created from SP version. (RWC)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: i
integer(kind=ip), intent(in) :: imax
integer(kind=ip), intent(in) :: m
integer(kind=ip), intent(in) :: mdw
integer(kind=ip), intent(inout) :: ipivot(*)
real(kind=wp), intent(inout) :: h(*)
real(kind=wp), intent(inout) :: w(mdw,*)
Calls
Called by
Source Code
   subroutine dwnlt3 (i, imax, m, mdw, ipivot, h, w)
   integer(ip),intent(in) :: i
   integer(ip),intent(in) :: imax
   integer(ip),intent(inout) :: ipivot(*)
   integer(ip),intent(in):: m
   integer(ip),intent(in) :: mdw
   real(wp),intent(inout) :: h(*)
   real(wp),intent(inout) :: w(mdw,*)
   real(wp) :: t
   integer(ip) :: itemp
   if (imax/=i) then
      itemp        = ipivot(i)
      ipivot(i)    = ipivot(imax)
      ipivot(imax) = itemp
      call dswap(m, w(1,imax), 1_ip, w(1,i), 1_ip)
      t       = h(imax)
      h(imax) = h(i)
      h(i)    = t
   endif
   end subroutine dwnlt3
Call graph
dwnlt3 calls dswap
dwnlit calls dwnlt3
dwnlsm calls dwnlit
dwnnls calls dwnlsm
dlpdp calls dwnnls
dlsi calls dlpdp
dlsei calls dlsi
dfcmn calls dlsei
dfc calls dfcmn