evaluate_4d – bspline-fortran
evaluate_4d Subroutine
20 statements
Source File
private pure subroutine evaluate_4d(me, xval, yval, zval, qval, idx, idy, idz, idq, f, iflag)
Evaluate a bspline_4d interpolate. This is a wrapper for db4val.
Type Bound
bspline_4d
Arguments
Type Intent Optional Attributes Name
class(bspline_4d), intent(inout) :: me
real(kind=wp), intent(in) :: xval
coordinate of evaluation point.
real(kind=wp), intent(in) :: yval
coordinate of evaluation point.
real(kind=wp), intent(in) :: zval
coordinate of evaluation point.
real(kind=wp), intent(in) :: qval
coordinate of evaluation point.
integer(kind=ip), intent(in) :: idx
derivative of piecewise polynomial to evaluate.
integer(kind=ip), intent(in) :: idy
derivative of piecewise polynomial to evaluate.
integer(kind=ip), intent(in) :: idz
derivative of piecewise polynomial to evaluate.
integer(kind=ip), intent(in) :: idq
derivative of piecewise polynomial to evaluate.
real(kind=wp), intent(out) :: f
interpolated value
integer(kind=ip), intent(out) :: iflag
status flag (see db4val)
Calls
Source Code
    pure subroutine evaluate_4d(me,xval,yval,zval,qval,idx,idy,idz,idq,f,iflag)
    implicit none
    class(bspline_4d),intent(inout) :: me
    real(wp),intent(in)             :: xval  !! \(x\) coordinate of evaluation point.
    real(wp),intent(in)             :: yval  !! \(y\) coordinate of evaluation point.
    real(wp),intent(in)             :: zval  !! \(z\) coordinate of evaluation point.
    real(wp),intent(in)             :: qval  !! \(q\) coordinate of evaluation point.
    integer(ip),intent(in)          :: idx   !! \(x\) derivative of piecewise polynomial to evaluate.
    integer(ip),intent(in)          :: idy   !! \(y\) derivative of piecewise polynomial to evaluate.
    integer(ip),intent(in)          :: idz   !! \(z\) derivative of piecewise polynomial to evaluate.
    integer(ip),intent(in)          :: idq   !! \(q\) derivative of piecewise polynomial to evaluate.
    real(wp),intent(out)            :: f     !! interpolated value
    integer(ip),intent(out)         :: iflag !! status flag (see [[db4val]])
    if (me%initialized) then
        call db4val(xval,yval,zval,qval,&
                    idx,idy,idz,idq,&
                    me%tx,me%ty,me%tz,me%tq,&
                    me%nx,me%ny,me%nz,me%nq,&
                    me%kx,me%ky,me%kz,me%kq,&
                    me%bcoef,f,iflag,&
                    me%inbvx,me%inbvy,me%inbvz,me%inbvq,&
                    me%iloy,me%iloz,me%iloq,&
                    me%work_val_1,me%work_val_2,me%work_val_3,me%work_val_4,&
                    extrap=me%extrap)
    else
        iflag = 1_ip
    end if
    me%iflag = iflag
    end subroutine evaluate_4d
Call graph
evaluate_4d calls db4val
db4val calls check_value, dbvalu, dintrv
dbvalu calls dintrv
dintrv calls get_temp_x_for_extrap