initialize_1d_auto_knots – bspline-fortran
initialize_1d_auto_knots Subroutine
25 statements
Source File
private pure subroutine initialize_1d_auto_knots(me, x, fcn, kx, iflag, extrap)
Initialize a bspline_1d type (with automatically-computed knots). This is a wrapper for db1ink.
Type Bound
bspline_1d
Arguments
Type Intent Optional Attributes Name
class(bspline_1d), intent(inout) :: me
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: fcn
(nx) array of function values to interpolate. fcn(i) should contain the function value at the point x(i)
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(out) :: iflag
status flag (see db1ink)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Calls
Called by
Contents
Source Code
initialize_1d_auto_knots
Source Code
    pure subroutine initialize_1d_auto_knots(me,x,fcn,kx,iflag,extrap)
    implicit none
    class(bspline_1d),intent(inout)  :: me
    real(wp),dimension(:),intent(in) :: x     !! `(nx)` array of \(x\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in) :: fcn   !! `(nx)` array of function values to interpolate. `fcn(i)` should
                                              !! contain the function value at the point `x(i)`
    integer(ip),intent(in)           :: kx    !! The order of spline pieces in \(x\)
                                              !! ( \( 2 \le k_x < n_x \) )
                                              !! (order = polynomial degree + 1)
    integer(ip),intent(out)          :: iflag !! status flag (see [[db1ink]])
    logical,intent(in),optional      :: extrap !! if true, then extrapolation is allowed
                                               !! (default is false)
    integer(ip) :: iknot
    integer(ip) :: nx
    call me%destroy()
    nx = size(x,kind=ip)
    me%nx = nx
    me%kx = kx
    allocate(me%tx(nx+kx))
    allocate(me%bcoef(nx))
    allocate(me%work_val_1(3_ip*kx))
    iknot = 0_ip         !knot sequence chosen by db1ink
    call db1ink(x,nx,fcn,kx,iknot,me%tx,me%bcoef,iflag)
    if (iflag==0_ip) then
        call me%set_extrap_flag(extrap)
    end if
    me%initialized = iflag==0_ip
    me%iflag = iflag
    end subroutine initialize_1d_auto_knots
Call graph
initialize_1d_auto_knots calls bcoef, destroy, db1ink, set_extrap_flag, tx, work_val_1
db1ink calls db1ink_alt, db1ink_alt_2, db1ink_default
db1ink_alt calls check_inputs, dbint4
db1ink_alt_2 calls check_inputs, dbint4
db1ink_default calls check_inputs, dbknot, dbtpcf
dbint4 calls dbnfac, dbnslv, dbspvd
dbtpcf calls dbintk, dbnslv
dbintk calls dbnfac, dbnslv, dbspvn
dbspvd calls dbspvn
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d calls bspline_1d_constructor_auto_knots