initialize_2d_auto_knots – bspline-fortran
initialize_2d_auto_knots Subroutine
32 statements
Source File
private pure subroutine initialize_2d_auto_knots(me, x, y, fcn, kx, ky, iflag, extrap)
Initialize a bspline_2d type (with automatically-computed knots). This is a wrapper for db2ink.
Type Bound
bspline_2d
Arguments
Type Intent Optional Attributes Name
class(bspline_2d), intent(inout) :: me
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:) :: fcn
(nx,ny) matrix of function values to interpolate. fcn(i,j) should contain the function value at the point (x(i),y(j))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(out) :: iflag
status flag (see db2ink)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Calls
Called by
Contents
Source Code
initialize_2d_auto_knots
Source Code
    pure subroutine initialize_2d_auto_knots(me,x,y,fcn,kx,ky,iflag,extrap)
    implicit none
    class(bspline_2d),intent(inout)    :: me
    real(wp),dimension(:),intent(in)   :: x     !! `(nx)` array of \(x\) abcissae. Must be strictly increasing.
    real(wp),dimension(:),intent(in)   :: y     !! `(ny)` array of \(y\) abcissae. Must be strictly increasing.
    real(wp),dimension(:,:),intent(in) :: fcn   !! `(nx,ny)` matrix of function values to interpolate.
                                                !! `fcn(i,j)` should contain the function value at the
                                                !! point (`x(i)`,`y(j)`)
    integer(ip),intent(in)             :: kx    !! The order of spline pieces in \(x\)
                                                !! ( \( 2 \le k_x < n_x \) )
                                                !! (order = polynomial degree + 1)
    integer(ip),intent(in)             :: ky    !! The order of spline pieces in \(y\)
                                                !! ( \( 2 \le k_y < n_y \) )
                                                !! (order = polynomial degree + 1)
    integer(ip),intent(out)            :: iflag !! status flag (see [[db2ink]])
    logical,intent(in),optional        :: extrap !! if true, then extrapolation is allowed
                                                 !! (default is false)
    integer(ip) :: iknot
    integer(ip) :: nx,ny
    call me%destroy()
    nx = size(x,kind=ip)
    ny = size(y,kind=ip)
    me%nx = nx
    me%ny = ny
    me%kx = kx
    me%ky = ky
    allocate(me%tx(nx+kx))
    allocate(me%ty(ny+ky))
    allocate(me%bcoef(nx,ny))
    allocate(me%work_val_1(ky))
    allocate(me%work_val_2(3_ip*max(kx,ky)))
    iknot = 0_ip         !knot sequence chosen by db2ink
    call db2ink(x,nx,y,ny,fcn,kx,ky,iknot,me%tx,me%ty,me%bcoef,iflag)
    if (iflag==0_ip) then
        call me%set_extrap_flag(extrap)
    end if
    me%initialized = iflag==0_ip
    me%iflag = iflag
    end subroutine initialize_2d_auto_knots
Call graph
initialize_2d_auto_knots calls bcoef, destroy, db2ink, set_extrap_flag, tx, ty, work_val_1, work_val_2
db2ink calls check_inputs, dbknot, dbtpcf
dbtpcf calls dbintk, dbnslv
dbintk calls dbnslv, dbnfac, dbspvn
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_2d calls bspline_2d_constructor_auto_knots