integral_1d – bspline-fortran
integral_1d Subroutine
14 statements
Source File
private pure subroutine integral_1d(me, x1, x2, f, iflag)
Evaluate a bspline_1d definite integral. This is a wrapper for db1sqad.
Arguments
Type Intent Optional Attributes Name
class(bspline_1d), intent(inout) :: me
real(kind=wp), intent(in) :: x1
left point of interval
real(kind=wp), intent(in) :: x2
right point of interval
real(kind=wp), intent(out) :: f
integral of the b-spline over
integer(kind=ip), intent(out) :: iflag
status flag (see db1sqad)
Calls
Contents
Source Code
integral_1d
Source Code
    pure subroutine integral_1d(me,x1,x2,f,iflag)
    implicit none
    class(bspline_1d),intent(inout) :: me
    real(wp),intent(in)             :: x1    !! left point of interval
    real(wp),intent(in)             :: x2    !! right point of interval
    real(wp),intent(out)            :: f     !! integral of the b-spline over \( [x_1, x_2] \)
    integer(ip),intent(out)         :: iflag !! status flag (see [[db1sqad]])
    if (me%initialized) then
        call db1sqad(me%tx,me%bcoef,me%nx,me%kx,x1,x2,f,iflag,me%work_val_1)
    else
        iflag = 1_ip
    end if
    me%iflag = iflag
    end subroutine integral_1d
Call graph
integral_1d calls db1sqad
db1sqad calls dbsqad
dbsqad calls dintrv, dbvalu
dintrv calls get_temp_x_for_extrap
dbvalu calls dintrv