set_extrap_flag – bspline-fortran
set_extrap_flag Subroutine
10 statements
Source File
private pure subroutine set_extrap_flag(me, extrap)
Sets the extrap flag in the class.
Type Bound
bspline_class
Arguments
Type Intent Optional Attributes Name
class(bspline_class), intent(inout) :: me
logical, intent(in), optional :: extrap
if not present, then False is used
Called by
Source Code
    pure subroutine set_extrap_flag(me,extrap)
    implicit none
    class(bspline_class),intent(inout) :: me
    logical,intent(in),optional :: extrap  !! if not present, then False is used
    if (present(extrap)) then
        me%extrap = extrap
    else
        me%extrap = .false.
    end if
    end subroutine set_extrap_flag
Call graph
initialize_1d_auto_knots calls set_extrap_flag
initialize_1d_specify_knots calls set_extrap_flag
initialize_2d_auto_knots calls set_extrap_flag
initialize_2d_specify_knots calls set_extrap_flag
initialize_3d_auto_knots calls set_extrap_flag
initialize_3d_specify_knots calls set_extrap_flag
initialize_4d_auto_knots calls set_extrap_flag
initialize_4d_specify_knots calls set_extrap_flag
initialize_5d_auto_knots calls set_extrap_flag
initialize_5d_specify_knots calls set_extrap_flag
initialize_6d_auto_knots calls set_extrap_flag
initialize_6d_specify_knots calls set_extrap_flag
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_2d_constructor_specify_knots calls initialize_2d_specify_knots
bspline_3d_constructor_auto_knots calls initialize_3d_auto_knots
bspline_3d_constructor_specify_knots calls initialize_3d_specify_knots
bspline_4d_constructor_auto_knots calls initialize_4d_auto_knots
bspline_4d_constructor_specify_knots calls initialize_4d_specify_knots
bspline_5d_constructor_auto_knots calls initialize_5d_auto_knots
bspline_5d_constructor_specify_knots calls initialize_5d_specify_knots
bspline_6d_constructor_auto_knots calls initialize_6d_auto_knots
bspline_6d_constructor_specify_knots calls initialize_6d_specify_knots
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_specify_knots
bspline_2d calls bspline_2d_constructor_auto_knots, bspline_2d_constructor_specify_knots
bspline_3d calls bspline_3d_constructor_auto_knots, bspline_3d_constructor_specify_knots
bspline_4d calls bspline_4d_constructor_auto_knots, bspline_4d_constructor_specify_knots
bspline_5d calls bspline_5d_constructor_auto_knots, bspline_5d_constructor_specify_knots
bspline_6d calls bspline_6d_constructor_auto_knots, bspline_6d_constructor_specify_knots