bspline_6d – bspline-fortran
bspline_6d Interface
3 statements
Source File
public interface bspline_6d
Constructor for bspline_6d
Calls
Contents
Module Procedures
bspline_6d_constructor_empty bspline_6d_constructor_auto_knots bspline_6d_constructor_specify_knots
Module Procedures
private elemental function bspline_6d_constructor_empty() result(me)
It returns an empty bspline_6d type. Note that INITIALIZE still needs to be called before it can be used. Not really that useful except perhaps in some OpenMP applications.
Arguments
None
Return Value type(bspline_6d)
private pure function bspline_6d_constructor_auto_knots(x, y, z, q, r, s, fcn, kx, ky, kz, kq, kr, ks, extrap) result(me)
Constructor for a bspline_6d type (auto knots). This is a wrapper for initialize_6d_auto_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: z
(nz) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: q
(nq) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: r
(nr) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: s
(ns) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:,:,:,:,:) :: fcn
(nx,ny,nz,nq,nr,ns) matrix of function values to interpolate. fcn(i,j,k,l,m,n) should contain the function value at the point (x(i),y(j),z(k),q(l),r(m),s(n))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kz
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kq
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kr
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ks
The order of spline pieces in () (order = polynomial degree + 1)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_6d)
private pure function bspline_6d_constructor_specify_knots(x, y, z, q, r, s, fcn, kx, ky, kz, kq, kr, ks, tx, ty, tz, tq, tr, ts, extrap) result(me)
Constructor for a bspline_6d type (user-specified knots). This is a wrapper for initialize_6d_specify_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: z
(nz) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: q
(nq) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: r
(nr) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: s
(ns) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:,:,:,:,:) :: fcn
(nx,ny,nz,nq,nr,ns) matrix of function values to interpolate. fcn(i,j,k,l,m,n) should contain the function value at the point (x(i),y(j),z(k),q(l),r(m),s(n))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kz
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kq
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kr
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ks
The order of spline pieces in () (order = polynomial degree + 1)
real(kind=wp), intent(in), dimension(:) :: tx
The (nx+kx) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: ty
The (ny+ky) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: tz
The (nz+kz) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: tq
The (nq+kq) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: tr
The (nr+kr) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: ts
The (ns+ks) knots in the direction for the spline interpolant. Must be non-decreasing.
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_6d)
Call graph
bspline_6d calls bspline_6d_constructor_auto_knots, bspline_6d_constructor_empty, bspline_6d_constructor_specify_knots
bspline_6d_constructor_auto_knots calls initialize_6d_auto_knots
bspline_6d_constructor_specify_knots calls initialize_6d_specify_knots
initialize_6d_auto_knots calls bcoef, destroy, db6ink, set_extrap_flag, tq, tr, ts, tx, ty, tz, work_val_1, work_val_2, work_val_3, work_val_4, work_val_5, work_val_6
initialize_6d_specify_knots calls bcoef, destroy, check_knot_vectors_sizes, db6ink, set_extrap_flag, work_val_1, work_val_2, work_val_3, work_val_4, work_val_5, work_val_6
db6ink calls check_inputs, dbknot, dbtpcf
dbtpcf calls dbintk, dbnslv
dbintk calls dbnslv, dbnfac, dbspvn