bspline_2d – bspline-fortran
bspline_2d Interface
3 statements
Source File
public interface bspline_2d
Constructor for bspline_2d
Calls
Contents
Module Procedures
bspline_2d_constructor_empty bspline_2d_constructor_auto_knots bspline_2d_constructor_specify_knots
Module Procedures
private elemental function bspline_2d_constructor_empty() result(me)
It returns an empty bspline_2d type. Note that INITIALIZE still needs to be called before it can be used. Not really that useful except perhaps in some OpenMP applications.
Arguments
None
Return Value type(bspline_2d)
private pure function bspline_2d_constructor_auto_knots(x, y, fcn, kx, ky, extrap) result(me)
Constructor for a bspline_2d type (auto knots). This is a wrapper for initialize_2d_auto_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:) :: fcn
(nx,ny) matrix of function values to interpolate. fcn(i,j) should contain the function value at the point (x(i),y(j))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_2d)
private pure function bspline_2d_constructor_specify_knots(x, y, fcn, kx, ky, tx, ty, extrap) result(me)
Constructor for a bspline_2d type (user-specified knots). This is a wrapper for initialize_2d_specify_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:) :: fcn
(nx,ny) matrix of function values to interpolate. fcn(i,j) should contain the function value at the point (x(i),y(j))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
real(kind=wp), intent(in), dimension(:) :: tx
The (nx+kx) knots in the direction for the spline interpolant. Must be non-decreasing.
real(kind=wp), intent(in), dimension(:) :: ty
The (ny+ky) knots in the direction for the spline interpolant. Must be non-decreasing.
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_2d)
Call graph
bspline_2d calls bspline_2d_constructor_auto_knots, bspline_2d_constructor_empty, bspline_2d_constructor_specify_knots
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_2d_constructor_specify_knots calls initialize_2d_specify_knots
initialize_2d_auto_knots calls bcoef, destroy, db2ink, set_extrap_flag, tx, ty, work_val_1, work_val_2
initialize_2d_specify_knots calls bcoef, destroy, check_knot_vectors_sizes, db2ink, set_extrap_flag, work_val_1, work_val_2
db2ink calls check_inputs, dbknot, dbtpcf
dbtpcf calls dbintk, dbnslv
dbintk calls dbnslv, dbnfac, dbspvn