bspline_1d – bspline-fortran
bspline_1d Interface
3 statements
Source File
public interface bspline_1d
Constructor for bspline_1d
Calls
Contents
Module Procedures
bspline_1d_constructor_empty bspline_1d_constructor_auto_knots bspline_1d_constructor_specify_knots
Module Procedures
private pure elemental function bspline_1d_constructor_empty() result(me)
It returns an empty bspline_1d type. Note that INITIALIZE still needs to be called before it can be used. Not really that useful except perhaps in some OpenMP applications.
Arguments
None
Return Value type(bspline_1d)
private pure function bspline_1d_constructor_auto_knots(x, fcn, kx, extrap) result(me)
Constructor for a bspline_1d type (auto knots). This is a wrapper for initialize_1d_auto_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: fcn
(nx) array of function values to interpolate. fcn(i) should contain the function value at the point x(i)
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_1d)
private pure function bspline_1d_constructor_specify_knots(x, fcn, kx, tx, extrap) result(me)
Constructor for a bspline_1d type (user-specified knots). This is a wrapper for initialize_1d_specify_knots.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: fcn
(nx) array of function values to interpolate. fcn(i) should contain the function value at the point x(i)
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
real(kind=wp), intent(in), dimension(:) :: tx
The (nx+kx) knots in the direction for the spline interpolant. Must be non-decreasing.
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Return Value type(bspline_1d)
Call graph
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_empty, bspline_1d_constructor_specify_knots
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
initialize_1d_auto_knots calls bcoef, destroy, db1ink, set_extrap_flag, tx, work_val_1
initialize_1d_specify_knots calls bcoef, destroy, db1ink, check_knot_vectors_sizes, set_extrap_flag, work_val_1
db1ink calls db1ink_alt, db1ink_alt_2, db1ink_default
db1ink_alt calls check_inputs, dbint4
db1ink_alt_2 calls check_inputs, dbint4
db1ink_default calls check_inputs, dbknot, dbtpcf
dbint4 calls dbnfac, dbnslv, dbspvd
dbtpcf calls dbintk, dbnslv
dbintk calls dbnfac, dbnslv, dbspvn
dbspvd calls dbspvn