db1ink – bspline-fortran
db1ink Interface
3 statements
Source File
public interface db1ink
1D initialization routines.
Calls
Called by
Contents
Module Procedures
db1ink_default db1ink_alt db1ink_alt_2
Module Procedures
private pure subroutine db1ink_default(x, nx, fcn, kx, iknot, tx, bcoef, iflag)
Determines the parameters of a function that interpolates the one-dimensional gridded data The interpolating function and its derivatives may subsequently be evaluated by the function db1val.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
integer(kind=ip), intent(in) :: nx
Number of abcissae
real(kind=wp), intent(in), dimension(:) :: fcn
(nx) array of function values to interpolate. fcn(i) should contain the function value at the point x(i)
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: iknot
knot sequence flag:
Read more…
real(kind=wp), intent(inout), dimension(:) :: tx
The (nx+kx) knots in the direction for the spline interpolant:
Read more…
real(kind=wp), intent(out), dimension(:) :: bcoef
(nx) array of coefficients of the b-spline interpolant.
integer(kind=ip), intent(out) :: iflag
status flag:
Read more…
private pure subroutine db1ink_alt(x, nx, fcn, kx, ibcl, ibcr, fbcl, fbcr, kntopt, tx, bcoef, iflag)
Alternate version of db1ink_default, where the boundary conditions can be specified.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
vector of abscissae of length nx, distinct and in increasing order
integer(kind=ip), intent(in) :: nx
number of data points,
real(kind=wp), intent(in), dimension(:) :: fcn
vector of ordinates of length nx
integer(kind=ip), intent(in) :: kx
spline order (Currently, this must be 4)
integer(kind=ip), intent(in) :: ibcl
selection parameter for left boundary condition:
Read more…
integer(kind=ip), intent(in) :: ibcr
selection parameter for right boundary condition:
Read more…
real(kind=wp), intent(in) :: fbcl
left boundary values governed by ibcl
real(kind=wp), intent(in) :: fbcr
right boundary values governed by ibcr
integer(kind=ip), intent(in) :: kntopt
knot selection parameter:
Read more…
real(kind=wp), intent(out), dimension(:) :: tx
knot array of length nx+6
real(kind=wp), intent(out), dimension(:) :: bcoef
b spline coefficient array of length nx+2
integer(kind=ip), intent(out) :: iflag
status flag:
Read more…
private pure subroutine db1ink_alt_2(x, nx, fcn, kx, ibcl, ibcr, fbcl, fbcr, tleft, tright, tx, bcoef, iflag)
Alternate version of db1ink_alt, where the first and last 3 knots are specified by the user.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
vector of abscissae of length nx, distinct and in increasing order
integer(kind=ip), intent(in) :: nx
number of data points,
real(kind=wp), intent(in), dimension(:) :: fcn
vector of ordinates of length nx
integer(kind=ip), intent(in) :: kx
spline order (Currently, this must be 4)
integer(kind=ip), intent(in) :: ibcl
selection parameter for left boundary condition:
Read more…
integer(kind=ip), intent(in) :: ibcr
selection parameter for right boundary condition:
Read more…
real(kind=wp), intent(in) :: fbcl
left boundary values governed by ibcl
real(kind=wp), intent(in) :: fbcr
right boundary values governed by ibcr
real(kind=wp), intent(in), dimension(3) :: tleft
t(1:3) in increasing order supplied by the user.
real(kind=wp), intent(in), dimension(3) :: tright
t(nx+4:nx+6) in increasing order supplied by the user.
real(kind=wp), intent(out), dimension(:) :: tx
knot array of length nx+6
real(kind=wp), intent(out), dimension(:) :: bcoef
b spline coefficient array of length nx+2
integer(kind=ip), intent(out) :: iflag
status flag:
Read more…
Call graph
db1ink calls db1ink_default, db1ink_alt_2, db1ink_alt
db1ink_default calls check_inputs, dbtpcf, dbknot
db1ink_alt_2 calls check_inputs, dbint4
db1ink_alt calls check_inputs, dbint4
dbtpcf calls dbintk, dbnslv
dbint4 calls dbnfac, dbnslv, dbspvd
dbintk calls dbnfac, dbnslv, dbspvn
dbspvd calls dbspvn
initialize_1d_auto_knots calls db1ink
initialize_1d_specify_knots calls db1ink
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_specify_knots