db1val – bspline-fortran
db1val Interface
3 statements
Source File
public interface db1val
1D evaluation routines.
Calls
Called by
Contents
Module Procedures
db1val_default db1val_alt
Module Procedures
private pure subroutine db1val_default(xval, idx, tx, nx, kx, bcoef, f, iflag, inbvx, w0, extrap)
Evaluates the tensor product piecewise polynomial interpolant constructed by the routine db1ink or one of its derivatives at the point xval.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: xval
coordinate of evaluation point.
integer(kind=ip), intent(in) :: idx
derivative of piecewise polynomial to evaluate.
real(kind=wp), intent(in), dimension(nx+kx) :: tx
sequence of knots defining the piecewise polynomial in the direction. (same as in last call to db1ink)
integer(kind=ip), intent(in) :: nx
the number of interpolation points in . (same as in last call to db1ink)
integer(kind=ip), intent(in) :: kx
order of polynomial pieces in . (same as in last call to db1ink)
real(kind=wp), intent(in), dimension(nx) :: bcoef
the b-spline coefficients computed by db1ink.
real(kind=wp), intent(out) :: f
interpolated value
integer(kind=ip), intent(out) :: iflag
status flag:
: no errors
: error
integer(kind=ip), intent(inout) :: inbvx
initialization parameter which must be set to 1 the first time this routine is called, and must not be changed by the user.
real(kind=wp), intent(inout), dimension(3_ip*kx) :: w0
work array
logical, intent(in), optional :: extrap
if extrapolation is allowed (if not present, default is False)
private pure subroutine db1val_alt(xval, idx, tx, nx, n, kx, bcoef, f, iflag, inbvx, w0, extrap)
Alternate version of db1val_default for use with db1ink_alt and db1ink_alt_2.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: xval
coordinate of evaluation point.
integer(kind=ip), intent(in) :: idx
derivative of piecewise polynomial to evaluate.
real(kind=wp), intent(in), dimension(n+kx) :: tx
sequence of knots defining the piecewise polynomial in the direction.
integer(kind=ip), intent(in) :: nx
the number of interpolation points in .
integer(kind=ip), intent(in) :: n
length of bcoef: nx+2
integer(kind=ip), intent(in) :: kx
order of polynomial pieces in . (same as in last call to db1ink)
real(kind=wp), intent(in), dimension(n) :: bcoef
the b-spline coefficients computed by db1ink.
real(kind=wp), intent(out) :: f
interpolated value
integer(kind=ip), intent(out) :: iflag
status flag:
: no errors
: error
integer(kind=ip), intent(inout) :: inbvx
initialization parameter which must be set to 1 the first time this routine is called, and must not be changed by the user.
real(kind=wp), intent(inout), dimension(3_ip*kx) :: w0
work array
logical, intent(in), optional :: extrap
if extrapolation is allowed (if not present, default is False)
Call graph
db1val calls db1val_default, db1val_alt
db1val_default calls check_value, dbvalu
db1val_alt calls check_value, dbvalu
dbvalu calls dintrv
dintrv calls get_temp_x_for_extrap
evaluate_1d calls db1val